Convert project to es modules
zackad/prettier-plugin-twig-melody pull request #17
Opened 2024-04-10 07:25 UTC by rellafella

This is unfortunately all in one giant commit, I noticed you already had a PR open for this so if this doesn't get merged I thought at least you might find some of the aspects useful.

My main issues were around getting jest to behave with es modules, from what I could tell generally people will keep the project type as commonjs when using jest, but they will just convert files to esm as they need to.

I have converted the test suite to use vitetest instead.

As far as updates go outside of the usual require and module.exports cleanup I have made some notes below where there have been any significant improvements.

- Moved switch plugin from the tests dir to the src dir to keep the tests clean
- (src/plugins/switch-plugin/index.js) not sure if I have got the exports right here, but it seems to work...
- (src/util/pluginUtil.js) handling the dynamic import for plugins has been changed a bit to handle the Promise resolution in ESM

2024-04-12 04:37 UTC, zackad commented
LGTM. Test failed on prettier version 2 which personally I want to drop the support. Not sure what people think, should we keep compatibility with prettier 2 or drop it?

2024-04-12 04:52 UTC, rellafella commented
I would rather see this move forward than have optimal backwards compatibility to be honest. However I might be able to take a look on the weekend to see what it would take to specify both an `index.js` and a `index.cjs` entry point. Pretty sure that would solve the install issue, but not sure that the code would be fully backwards compatible with common js, definitely not a module expert.

2024-04-14 23:30 UTC, zackad commented
> However I might be able to take a look on the weekend to see what it would take to specify both an `index.js` and a `index.cjs` entry point. Pretty sure that would solve the install issue, but not sure that the code would be fully backwards compatible with common js, definitely not a module expert.

The way I see it, we might need to add build step before publishing into npm registry. Similar to how [trivago/melody](https://github.com/trivago/melody) handling support for commonjs and es module.

OTOH, there's problem with plugin system. Here what the output when loading `switch-plugin`

__CommonJS__
```
{% switch matrixBlock.type %}
    {% case 'text' %}
        {{ matrixBlock.textField|markdown }}
    {% case 'image' %}
        {{ matrixBlock.image[0].getImg() }}
    {% default %}
        <p>
            A font walks into a bar.
        </p>
        <p>
            The bartender says, “Hey, we don’t serve your type in here!”
        </p>
{% endswitch %}
```

__ES Module__
```
{% switch matrixBlock.type %}
{% case 'text' %}
    {{ matrixBlock.textField|markdown }}
{% case 'image' %}
    {{ matrixBlock.image[0].getImg() }}
{% default %}
    <p>
        A font walks into a bar.
    </p>
    <p>
        The bartender says, “Hey, we don’t serve your type in here!”
    </p>
{% endswitch %}
```

Still can't figure it out what the actual problem are.

2024-04-15 05:57 UTC, rellafella commented
That's a good catch, i'll investigate here, I think this probably has something to do with this export, whilst being valid I don't think it is correct.
https://github.com/zackad/prettier-plugin-twig-melody/blob/bcc1e020c5c0356e7d209e8e2bd7d9ac5faedb2e/src/plugins/switch-plugin/index.js#L33-L35

2024-04-15 11:32 UTC, zackad commented on src/util/pluginUtil.js
>      }
I think the problem is how plugin being loaded. I can't even make the plugin to be executed. The variable `result` returning an empty array. Tried `async/await` function and still no success.

Something like this and other variation doesn't seems to work.
```js
return pluginPaths.map(async pluginPath => await tryLoadPlugin(pluginPath));
```

2024-04-26 23:23 UTC, zackad requested changes
I've partially applied your changes into separate commit/pull request. All that left is actually rewrite into es module. Would you be able to rebase?

Some notes:
- revert changes to snapshot test file. rewriting should not modify actual test result.
- revert change on `flake.nix`, unrelated
- add `.eslintcache` into `.gitignore`

Thank you.

2024-04-26 23:23 UTC, zackad commented on .eslintcache
please add this file into `.gitignore`

2024-04-26 23:23 UTC, zackad commented on flake.nix
revert this file, unrelated change

2024-04-30 04:11 UTC, rellafella commented on .eslintcache
alternatively happy to just revert the lint script back to 
`"lint": "DEBUG=eslint:cli-engine eslint .",`

2024-04-30 23:30 UTC, rellafella commented
I am going back over this with some proper attention to detail. Do you have a preference on using or avoiding default exports?

2024-05-01 02:06 UTC, zackad commented
I have preference to keep the changes to be as minimal as possible. Unfortunately your changes is not exactly compatible with existing plugin functionality as you can see from modified snapshot file.

Regarding plugin system, I'm not sure if I want to keep this feature. The `switch-plugin` is not a twig feature AFAIK. Personally I want to remove plugin system. Do people actually use it? What do you think?

I haven't test it on my local machine (hopefully this weekend).

2024-05-01 02:18 UTC, rellafella commented
I am just working on it now actually stand by for some updates to this branch. 

I think that is a valid suggestion to just scrap the plugin functionality or at least remove it for now, to perhaps add it in later if it is going to stall further development.

Whilst the `switch-plugin` isn't part of twig, it is part of Craft CMS (since at least 2.0.0) which is a common use case for this prettier plugin.

Out of curiosity what system are you using Twig for and does that come bundled with some custom Twig extensions that you want to include?

## Craft CMS docs for tags
https://craftcms.com/docs/2.x/templating/switch.html
https://craftcms.com/docs/3.x/dev/tags.html
https://craftcms.com/docs/4.x/dev/tags.html
https://craftcms.com/docs/5.x/reference/twig/tags.html

2024-05-01 03:45 UTC, zackad commented
I'm using twig with symfony framework. Didn't know about twig use case outside symfony framework ecosystem. Knowing this, I don't want to break existing functionality (atleast without offering some alternatives).

For now I want to keep all features as-is. Extension/features I want to add in the future includes:
- all the feature from original twig templating engine
- features from [twig component](https://symfony.com/bundles/ux-twig-component/current/index.html)

2024-05-03 03:29 UTC, rellafella commented
I would say the easiest way would be to just scrap the plugin utility and move to an approach where that functionality is built into the core

2024-05-03 05:07 UTC, rellafella commented
I have updated the PR with an example of what this would look like without the plugin feature and the switch tag print just rolled directly into the core

2024-05-04 00:53 UTC, zackad approved these changes

2024-05-04 00:55 UTC, merged

2024-05-04 00:57 UTC, zackad commented
Thank you @rellafella